spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - addAuthenticationHeader
            - id: question-service
              uri: lb://question-service
              predicates:
                - Path=/api/questions/**
              filters:
                - addAuthenticationHeader
            - id: answer-service
              uri: lb://answer-service
              predicates:
                - Path=/api/answers/**
              filters:
                - addAuthenticationHeader
            - id: ai-feedback-service
              uri: lb://ai-feedback-service
              predicates:
                - Path=/api/ai-feedback/**
              filters:
                - addAuthenticationHeader
            - id: statistic-service
              uri: lb://statistic-service
              predicates:
                - Path=/api/statistics/**
              filters:
                - addAuthenticationHeader

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS:api-gateway}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}