spring:
  application:
    name: answer-service
  datasource:
    url: jdbc:mysql://localhost:3308/answer_service?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: answer_service
    password: ${ANSWER_DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true