eureka:
  instance:
    hostname: eureka-server  # Docker 컨테이너명
    prefer-ip-address: true

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true  # Docker에서는 활성화
    eviction-interval-timer-in-ms: 30000  # 30초
    renewal-percent-threshold: 0.85

# Docker 환경용 로깅
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO