spring:
  application:
    name: ai-feedback-service

server:
  port: 8084

gemini:
  api:
    key: ${GEMINI_API_KEY}
    model: gemini-2.0-flash
    timeout: 30s

# 임시로 설정
eureka:
  client:
    enabled: false